OVERTIME.MANAGER.MAIN/ViewModels/OvertimeAdd.cs
using OVERTIME.MANAGER.MAIN.Models;
using X.PagedList;

namespace OVERTIME.MANAGER.MAIN.ViewModels
{
    public class OvertimeAdd
    {
        #nullable disable
        public Overtime overtime { get; set; }
        public PagedList<Employee> list { get; set; }
        public string searchQuery { get; set; }
        public int pageIndex { get; set; } = 1;
        public int pageSize { get; set; } = 15;
        public int totalRecord { get; set; } = 0;
    }
}

OVERTIME.MANAGER.MAIN/Controllers/OvertimeManagerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using OVERTIME.MANAGER.MAIN.Models;
using OVERTIME.MANAGER.MAIN.Utils.Enums;
using OVERTIME.MANAGER.MAIN.ViewModels;
using System.Data;
using X.PagedList;

namespace OVERTIME.MANAGER.MAIN.Controllers
{
    public class OvertimeManagerController : Controller
    {
#nullable disable
        private readonly OvertimeManagerContext db = new OvertimeManagerContext();

        /// <summary>
        /// Hàm filter, sort and paging
        /// </summary>
        /// <param name="pageIndex">Trang hiện tại</param>
        /// <param name="pageSize">Số bản ghi trên trang</param>
        /// <param name="searchQuery">Giá trị tìm kiếm</param>
        /// <param name="status">Trạng thái đơn làm thêm</param>
        /// <returns>Danh sách đơn làm thêm thỏa mãn điều kiện lọc</returns>
        ///
        [Authentication]
        public IActionResult Index(string searchQuery = "", int pageIndex = 1, int pageSize = 15, Byte status = 3)
        {
            IEnumerable<Overtime> lstOvertime;
            Employee temp = db.Employees.FirstOrDefault(x => x.Account.Equals(HttpContext.Session.GetString("Account")));

            if (temp != null && temp.EmployeeRole == (int)Role.normal)
            {
                lstOvertime = db.Overtimes.AsNoTracking().Where(x => (x.EmployeeId == temp.EmployeeId) && (x.EmployeeName.ToLower().Contains(searchQuery.ToLower()) || x.EmployeeCode.ToLower().Contains(searchQuery.ToLower()) || x.JobPositionName.ToLower().Contains(searchQuery.ToLower()) || x.OrganizationName.ToLower().Contains(searchQuery.ToLower())) && (x.StatusOvertime == status)).OrderByDescending(x => x.ModifiedDate);
            }
            else
            {
                lstOvertime = db.Overtimes.AsNoTracking().Where(x => (x.EmployeeName.ToLower().Contains(searchQuery.ToLower()) || x.EmployeeCode.ToLower().Contains(searchQuery.ToLower()) || x.JobPositionName.ToLower().Contains(searchQuery.ToLower()) || x.OrganizationName.ToLower().Contains(searchQuery.ToLower())) && (x.StatusOvertime == status)).OrderByDescending(x => x.ModifiedDate);
            }

            if (status == 3)
            {
                if (temp != null && temp.EmployeeRole == (int)Role.normal)
                {
                    lstOvertime = db.Overtimes.AsNoTracking().Where(x => (x.EmployeeId.Equals(temp.EmployeeId)) && (x.EmployeeName.ToLower().Contains(searchQuery.ToLower()) || x.EmployeeCode.ToLower().Contains(searchQuery.ToLower()) || x.JobPositionName.ToLower().Contains(searchQuery.ToLower()) || x.OrganizationName.ToLower().Contains(searchQuery.ToLower()))).OrderByDescending(x => x.ModifiedDate);
                }
                else
                {
                    lstOvertime = db.Overtimes.AsNoTracking().Where(x => x.EmployeeName.ToLower().Contains(searchQuery.ToLower()) || x.EmployeeCode.ToLower().Contains(searchQuery.ToLower()) || x.JobPositionName.ToLower().Contains(searchQuery.ToLower()) || x.OrganizationName.ToLower().Contains(searchQuery.ToLower())).OrderByDescending(x => x.ModifiedDate);
                }
            }

            ListItem<Overtime> lst = new ListItem<Overtime>()
            {
                list = new PagedList<Overtime>(lstOvertime, pageIndex, pageSize),
                searchQuery = searchQuery,
                pageIndex = pageIndex,
                pageSize = pageSize,
                status = status,
                totalRecord = lstOvertime.Count(),
            };

            ViewBag.PageSizes = GetSelectListItems(SelectedItem.pageSize);
            ViewBag.Statuses = GetSelectListItems(SelectedItem.status);

            return View(lst);
        }

        /// <summary>
        /// Chi tiết đơn làm thêm
        /// </summary>
        /// <param name="overtimeId">ID đơn làm thêm</param>
        /// 
        [Authentication]
        public IActionResult OvertimeDetail(string overtimeId)
        {
            Overtime overtimeDetail = db.Overtimes.AsNoTracking().FirstOrDefault(x => x.OverTimeId == overtimeId);

            return View(overtimeDetail);
        }

        /// <summary>
        /// Thêm đơn làm thêm mới
        /// </summary>
        /// 
        [HttpGet]
        [Authentication]
        public IActionResult OvertimeAdd()
        {
            ViewBag.Employees = GetSelectListItems(SelectedItem.employee);
            ViewBag.WorkingShifts = GetSelectListItems(SelectedItem.workingshift);
            ViewBag.OWs = GetSelectListItems(SelectedItem.overtime_workingshift);
            ViewBag.Approvals = GetSelectListItems(SelectedItem.approval);
            ViewBag.StatusOvertimes = GetSelectListItems(SelectedItem.status_overtime);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]
        public IActionResult OvertimeAdd(Overtime ot)
        {
            DateTime now = DateTime.Now;
            string employeeID = ot.EmployeeName;
            string workingShiftID = ot.WorkingShiftName;
            string owsID = ot.OverTimeInWorkingShiftName;
            string approvalID = ot.ApprovalName;

            ot.OverTimeId = Guid.NewGuid().ToString();
            ot.ModifiedBy = "nnhiep";
            ot.CreatedBy = "nnhiep";
            ot.ModifiedDate = now;
            ot.CreatedDate = now;
            ot.EmployeeId = employeeID;
            ot.OverTimeInWorkingShiftId = owsID;
            ot.WorkingShiftId = workingShiftID;
            ot.ApprovalId = approvalID;
            ot.OverTimeEmployeeIds = ot.OverTimeEmployeeIds ?? "";
            ot.OverTimeEmployeeCodes = ot.OverTimeEmployeeCodes ?? "";
            ot.OverTimeEmployeeNames = ot.OverTimeEmployeeNames ?? "";
            ot.EmployeeCode = db.Employees.AsNoTracking().FirstOrDefault(x => x.EmployeeId == employeeID).EmployeeCode;
            ot.EmployeeName = db.Employees.AsNoTracking().FirstOrDefault(x => x.EmployeeId == employeeID).EmployeeName;
            ot.JobPositionId = db.Employees.AsNoTracking().FirstOrDefault(x => x.EmployeeId == employeeID).JobPositionId;
            ot.JobPositionName = db.Employees.AsNoTracking().FirstOrDefault(x => x.EmployeeId == employeeID).JobPositionName;
            ot.OverTimeInWorkingShiftCode = db.OverTimeInWorkingShifts.AsNoTracking().FirstOrDefault(x => x.OverTimeInWorkingShiftId == owsID).OverTimeInWorkingShiftCode;
            ot.OverTimeInWorkingShiftName = db.OverTimeInWorkingShifts.AsNoTracking().FirstOrDefault(x => x.OverTimeInWorkingShiftId == owsID).OverTimeInWorkingShiftName;
            ot.WorkingShiftCode = db.WorkingShifts.AsNoTracking().FirstOrDefault(x => x.WorkingShiftId == workingShiftID).WorkingShiftCode;
            ot.WorkingShiftName = db.WorkingShifts.AsNoTracking().FirstOrDefault(x => x.WorkingShiftId == workingShiftID).WorkingShiftName;
            ot.ApprovalName = db.Employees.AsNoTracking().FirstOrDefault(x => x.EmployeeId == approvalID).EmployeeName;
            ot.Employee = db.Employees.FirstOrDefault(x => x.EmployeeId == employeeID);
            ot.JobPosition = db.JobPositions.FirstOrDefault(x => x.JobPositionId == ot.JobPositionId);
            ot.Organization = db.Organizations.FirstOrDefault(x => x.OrganizationId == ot.OrganizationId);
            ot.Approval = db.Employees.FirstOrDefault(x => x.EmployeeId == approvalID);
            ot.WorkingShift = db.WorkingShifts.FirstOrDefault(x => x.WorkingShiftId == workingShiftID);
            ot.OverTimeInWorkingShift = db.OverTimeInWorkingShifts.FirstOrDefault(x => x.OverTimeInWorkingShiftId == owsID);

            try
            {
                db.Overtimes.Add(ot);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);

                ViewBag.Employees = GetSelectListItems(SelectedItem.employee);
                ViewBag.WorkingShifts = GetSelectListItems(SelectedItem.workingshift);
                ViewBag.OWs = GetSelectListItems(SelectedItem.overtime_workingshift);
                ViewBag.Approvals = GetSelectListItems(SelectedItem.approval);
                ViewBag.StatusOvertimes = GetSelectListItems(SelectedItem.status_overtime);

                return View(ot);
            }
        }

        /// <summary>
        /// Sửa thông tin đơn làm thêm
        /// </summary>
        /// <returns></returns>
        [Authentication]
        [HttpGet]
        public IActionResult OvertimeUpdate(string overtimeId, bool isDuplicate)
        {
            if (isDuplicate == true)
            {
                ViewBag.isDuplicate = true;
            }

            Overtime ot = db.Overtimes.AsNoTracking().FirstOrDefault(x => x.OverTimeId == overtimeId);

            ViewBag.Employees = GetSelectListItems(SelectedItem.employee);
            ViewBag.WorkingShifts = GetSelectListItems(SelectedItem.workingshift);
            ViewBag.OWs = GetSelectListItems(SelectedItem.overtime_workingshift);
            ViewBag.Approvals = GetSelectListItems(SelectedItem.approval);
            ViewBag.StatusOvertimes = GetSelectListItems(SelectedItem.status_overtime);

            return View(ot);
        }

        [HttpPost]
        [Authentication]
        [ValidateAntiForgeryToken]
        public IActionResult OvertimeUpdate(Overtime ot, bool isDuplicate)
        {
            DateTime now = DateTime.Now;

            if (ot.StatusOvertime == (int)OvertimeStatus.approved || ot.StatusOvertime == (int)OvertimeStatus.refused)
            {
                return RedirectToAction("DontHavePermission", "Home");
            }

            if (isDuplicate == true)
            {
                ot.OverTimeId = Guid.NewGuid().ToString();
            }

            ot.ModifiedBy = "nnhiep";
            ot.ModifiedDate = now;
            ot.OverTimeEmployeeIds = ot.OverTimeEmployeeIds ?? "";

OVERTIME.MANAGER.MAIN/Views/OvertimeManager/AddJobPositionManager.cshtml
@model OVERTIME.MANAGER.MAIN.Models.JobPosition
@using OVERTIME.MANAGER.MAIN.ViewModels;

@{
    ViewData["Title"] = "Quản lý vị trí công việc";
    Layout = "~/Views/Shared/_LayoutDefault.cshtml";
    var navigatorActive = new NavigatorActive { navigatorActive = "EmployeeManager" };
}

@section header
{
    <partial name="~/Views/OvertimeManager/_HeaderOM.cshtml" model="navigatorActive" />
}

@section link {
    <link rel="stylesheet" href="../assets/components/overtime_add/css/style.css" />
}

<main class="container-fluid overtime-main">
    <div class="overtime-wrapper py-3">
        <!-- Heading -->
        <div class="overtime-heading d-flex align-items-center justify-content-between pb-3">
            <div class="heading-left">
                <a asp-action="JobPositionManager" asp-controller="OvertimeManager"><i class="fa-solid fa-arrow-left"></i></a>
                <div class="fs-5 fw-bold heading-title"> Job Position Add</div>
            </div>
            <div class="btn-group-wrapper">
                <a type="button" class="btn btn-danger btn-add" asp-controller="OvertimeManager" asp-action="JobPositionManager">
                    <span>Cancel</span>
                </a>
            </div>
        </div>

        <!-- Content -->
        <div class="overtime-container-detail overtime-container-add">
            <div class="row">
                <div class="col-md-4">
            <form asp-action="AddJobPositionManager">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="JobPositionCode" class="control-label"></label>
                    <input asp-for="JobPositionCode" class="form-control" />
                    <span asp-validation-for="JobPositionCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="JobPositionName" class="control-label"></label>
                    <input asp-for="JobPositionName" class="form-control" />
                    <span asp-validation-for="JobPositionName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreatedDate" class="control-label"></label>
                    <input asp-for="CreatedDate" class="form-control" />
                    <span asp-validation-for="CreatedDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreatedBy" class="control-label"></label>
                    <input asp-for="CreatedBy" class="form-control" />
                    <span asp-validation-for="CreatedBy" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ModifiedDate" class="control-label"></label>
                    <input asp-for="ModifiedDate" class="form-control" />
                    <span asp-validation-for="ModifiedDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ModifiedBy" class="control-label"></label>
                    <input asp-for="ModifiedBy" class="form-control" />
                    <span asp-validation-for="ModifiedBy" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
            
        </div>
     </div>
     </div>
     </div>
</main>

OVERTIME.MANAGER.MAIN/Views/OvertimeManager/AddOrganization.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model OVERTIME.MANAGER.MAIN.Models.Organization
@using OVERTIME.MANAGER.MAIN.ViewModels;


@{
    ViewData["Title"] = "Quản lý đơn vị công tác";
    Layout = "~/Views/Shared/_LayoutDefault.cshtml";
    var navigatorActive = new NavigatorActive { navigatorActive = "EmployeeManager" };
}


@section header
{
    <partial name="~/Views/OvertimeManager/_HeaderOM.cshtml" model="navigatorActive" />
}

@section link {
    <link rel="stylesheet" href="../assets/components/overtime_add/css/style.css" />
}

<main class="container-fluid overtime-main">
    <div class="overtime-wrapper py-3">
 <!-- Header -->
        <div class="overtime-heading d-flex align-items-center justify-content-between pb-3">
            <div class="heading-left">
                <a asp-action="AddOrganization" asp-controller="OvertimeManager"><i class="fa-solid fa-arrow-left"></i></a>
                <div class="fs-5 fw-bold heading-title"> AddOrganization</div>
            </div>
            <div class="btn-group-wrapper">
                <a type="button" class="btn btn-danger btn-add" asp-controller="OvertimeManager" asp-action="OrganizationManager">
                    <span>Cancel</span>
                </a>
            </div>
        </div>

<!--Phần chính-->
        <div class="overtime-container-detail overtime-container-add">
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="AddOrganization">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                            <label asp-for="OrganizationCode" class="control-label"></label>
                            <input asp-for="OrganizationCode" class="form-control" />
                            <span asp-validation-for="OrganizationCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                            <label asp-for="OrganizationName" class="control-label"></label>
                            <input asp-for="OrganizationName" class="form-control" />
                            <span asp-validation-for="OrganizationName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreatedDate" class="control-label"></label>
                    <input asp-for="CreatedDate" class="form-control" />
                    <span asp-validation-for="CreatedDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreatedBy" class="control-label"></label>
                    <input asp-for="CreatedBy" class="form-control" />
                    <span asp-validation-for="CreatedBy" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ModifiedDate" class="control-label"></label>
                    <input asp-for="ModifiedDate" class="form-control" />
                    <span asp-validation-for="ModifiedDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ModifiedBy" class="control-label"></label>
                    <input asp-for="ModifiedBy" class="form-control" />
                    <span asp-validation-for="ModifiedBy" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
            
        </div>
     </div>
     </div>
     </div>
</main>

OVERTIME.MANAGER.MAIN/Views/OvertimeManager/EditJobPositionManager.cshtml
@model OVERTIME.MANAGER.MAIN.Models.JobPosition

@using OVERTIME.MANAGER.MAIN.ViewModels;

@{
    ViewData["Title"] = "Quản lý vị trí công việc";
    Layout = "~/Views/Shared/_LayoutDefault.cshtml";
    var navigatorActive = new NavigatorActive { navigatorActive = "EmployeeManager" };
}

@section header
    {
        <partial name="~/Views/OvertimeManager/_HeaderOM.cshtml" model="navigatorActive" />
}


<main class="container-fluid overtime-main">
    <div class="overtime-wrapper py-3">
        <!-- Heading -->
        <div class="overtime-heading d-flex align-items-center justify-content-between pb-3">
            <div class="heading-left">
                <a asp-action="JobPositionManager" asp-controller="OvertimeManager"><i class="fa-solid fa-arrow-left"></i></a>
                <div class="fs-5 fw-bold heading-title"> Job Position Edit</div>
            </div>
            <div class="btn-group-wrapper">
                <a type="button" class="btn btn-danger btn-add" asp-controller="OvertimeManager" asp-action="JobPositionManager">
                    <span>Cancel</span>
                </a>
            </div>
        </div>

        <!-- Content -->
        <div class="overtime-container-detail overtime-container-add">
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="EditJobPositionManager">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="JobPositionId" />
                        <div class="form-group">
                            <label asp-for="JobPositionCode" class="control-label"></label>
                            <input asp-for="JobPositionCode" class="form-control" />
                            <span asp-validation-for="JobPositionCode" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="JobPositionName" class="control-label"></label>
                            <input asp-for="JobPositionName" class="form-control" />
                            <span asp-validation-for="JobPositionName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CreatedDate" class="control-label"></label>
                            <input asp-for="CreatedDate" class="form-control" />
                            <span asp-validation-for="CreatedDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CreatedBy" class="control-label"></label>
                            <input asp-for="CreatedBy" class="form-control" />
                            <span asp-validation-for="CreatedBy" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ModifiedDate" class="control-label"></label>
                            <input asp-for="ModifiedDate" class="form-control" />
                            <span asp-validation-for="ModifiedDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ModifiedBy" class="control-label"></label>
                            <input asp-for="ModifiedBy" class="form-control" />
                            <span asp-validation-for="ModifiedBy" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

OVERTIME.MANAGER.MAIN/Views/OvertimeManager/JobPositionManager.cshtml
@using OVERTIME.MANAGER.MAIN.ViewModels;
@using Microsoft.AspNetCore.Html;
@using X.PagedList.Mvc.Core
@using OVERTIME.MANAGER.MAIN.Utils.Enums;
@{
    ViewData["Title"] = "Quản lý vị trí công việc";
    Layout = "~/Views/Shared/_LayoutDefault.cshtml";
    var navigatorActive = new NavigatorActive { navigatorActive = "JobPositionManager" };
}

@section header
{
    <partial name="~/Views/OvertimeManager/_HeaderOM.cshtml" model="navigatorActive" />
}

@section link {
    <link rel="stylesheet" href="../assets/components/overtime/css/style.css" />
}

<main class="container-fluid overtime-main">
    <div class="overtime-wrapper py-3">
        <!-- Heading -->
        <div class="overtime-heading d-flex align-items-center justify-content-between pb-3">
            <div class="fs-5 fw-bold">Job Position Manager</div>
            <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                <a type="button" class="btn btn-primary btn-add" asp-controller="OvertimeManager" asp-action="AddJobPositionManager">
                    <i class="fa-solid fa-plus"></i>
                    <span>Add</span>
                </a>
                <div class="btn-group" role="group">
                    <button id="btnGroupDrop" type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
                    </button>
                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop">
                        <a class="dropdown-item" href="#">
                            <i class="fa-solid fa-file-import"></i>
                            <span class="ml-8">Import</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Content -->
        <div class="overtime-content flex-row align-items-center justify-content-between">
           

            <!-- Table -->
            <div class="overtime-table">
                    <table class="table table-hover">
                        <thead class="unselect">
                            <tr>
                                <th width="140px"></th>
                                <th width="100px">ID</th>
                                <th width="160px">Code</th>
                                <th width="120px">Name</th>
                                <th width="180px">Created Date</th>
                                <th width="120px">Created By</th>
                                <th width="180px">Modified Date</th>
                                <th width="120px">Modified By</th>
                                <th class="text-center">Status</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <input my-data="@item.JobPositionId" type="checkbox" />
                                    </td>
                                    <td>@item.JobPositionId</td>
                                    <td>@item.JobPositionCode</td>
                                    <td>@item.JobPositionName</td>
                                    <td>@item.CreatedDate</td>
                                    <td>@item.CreatedBy</td>
                                    <td>@item.ModifiedDate</td>
                                    <td>@item.ModifiedBy</td>
                                    <td class="overtime-action-wrapper">
                                    <a class="overtime-action" asp-controller="OvertimeManager" asp-action="EditJobPositionManager" asp-route-ma="@item.JobPositionId">
                                            <i class="fa-solid fa-circle-info"></i>
                                        </a>
                                    <a class="overtime-action delete" asp-action="DeleteJobPositionManager" asp-route-ma="@item.JobPositionId">
                                        <i class="fa-solid fa-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
            </div>

            <!-- Pagination-->
            <div class="overtime-pagination d-flex align-items-center justify-content-between">
                <div class="pagination-total">Total records: <b></b></div>
                <div class="pagination-paging d-flex align-items-center">
                    <div class="dropdown mr-20">
                        <select class="form-select pageSize-navigation" name="pageSize"  asp-items="@ViewBag.PageSizes">
                        </select>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</main>

@section script {
    <script src="../assets/components/overtime/js/script.js"></script>
    <script>
        // Focus vào input search khi vừa vào trang - nnhiep
        document.querySelector('.overtime-search')?.focus();

        // Ẩn/Hiển thị toolbar khi click chọn ít nhất một hàng bất kỳ - nnhiep
        document.querySelector('.overtime-table thead tr th:first-child')?.addEventListener('change', (e) => {
            if (e.target.checked) {
                document.querySelector('.overtime-toolbar-show').style.display = 'none';
                document.querySelector('.overtime-toolbar-hide').style.display = 'flex';
            } else {
                document.querySelector('.overtime-toolbar-hide').style.display = 'none';
                document.querySelector('.overtime-toolbar-show').style.display = 'flex';
            }
        })


        let selectedData = [];

        // Xử lý tick chọn hết trong table - nnhiep
        let checkAll = document.querySelector('.overtime-table table thead th:first-child input');
        checkAll?.addEventListener('change', (e) => {
            document.querySelectorAll('.overtime-table table tbody td:first-child input').forEach(item => {
                let selectedKey = item.getAttribute("my-data");
                item.checked = checkAll.checked;
                if (checkAll.checked) {
                    if (selectedData.indexOf(selectedKey) == -1) {
                        selectedData.push(selectedKey);
                    }
                } else {
                    selectedData = selectedData.filter(item => item !== selectedKey);
                }
            });
            document.querySelector('.selectedItem').innerHTML = selectedData.length;
        });
    </script>
}

OVERTIME.MANAGER.MAIN/Views/OvertimeManager/OrganizationManager.cshtml
@using OVERTIME.MANAGER.MAIN.ViewModels;
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<Organization>
@{
    ViewData["Title"] = "Quản lý đơn vị công tác";
    Layout = "~/Views/Shared/_LayoutDefault.cshtml";
    var navigatorActive = new NavigatorActive { navigatorActive = "OrganizationManager" };
}

@section header
{
    <partial name="~/Views/OvertimeManager/_HeaderOM.cshtml" model="navigatorActive" />
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<h1>OrganizationManager</h1>

<p>
    <a asp-action="AddOrganization" class="btn btn-primary">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                OrganizationCode
            </th>
            <th>
                OrganizationName
            </th>
            <th>
                CreatedDate
            </th>
            <th>
                CreatedBy
            </th>
            <th>
                ModifiedDate
            </th>
            <th>
                ModifiedBy
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrganizationCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrganizationName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModifiedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModifiedBy)
                </td>
                <td>
                    <a asp-action="EditOrganization" asp-route-ma="@item.OrganizationId" style="text-decoration: none">
                        <button type="button" class="btn-sm btn-gradient-danger" asp-action="Edit" asp-route-id="@item.OrganizationId">
                            Edit
                        </button>
                    </a>
                    <a asp-action="DeleteOrganization" asp-route-ma="@item.OrganizationId" style="text-decoration: none">
                        <button type="button" class="btn-sm btn-gradient-danger" asp-action="Delete" asp-route-id="@item.OrganizationId">
                            Delete
                        </button>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
@Html.PagedListPager(Model,page=>Url.Action("OrganizationManager",new {page=page}),new
X.PagedList.Web.Common.PagedListRenderOptions(){
    LiElementClasses = new List<String>{"page-item"},
    PageClasses = new List<String>{"page-link"}
})